# -*- coding: utf-8 -*-
"""BetterOne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOr5Mm9T_ejcyu9Q9KZcMJfYDyk9Gav5
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from matplotlib import pyplot as plt
# %matplotlib inline
import seaborn as sns
iris_df = sns.load_dataset('iris')
iris_df.head()

features  = iris_df.drop(['species'], axis=1)
labels = iris_df.filter(['species'], axis=1)
features.head()

from sklearn.cluster import AgglomerativeClustering
hc_model = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
hc_model.fit_predict(features)

print(hc_model.labels_)

plt.scatter(features[:,0], features[:, 1], c= hc_model.labels_, cmap='rainbow')

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
#adjusted_rand_score(labels_true, labels_pred)
print("ARI = ", adjusted_rand_score(labels_num, hc_model.labels_))

import scipy.cluster.hierarchy as shc
plt.figure(figsize=(10, 7))
plt.title("Iris Dendrogram")
dend = shc.dendrogram(shc.linkage(features, method='ward'))

plt.scatter(features[:,0], features[:,1], c=labels, cmap='rainbow')

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
#adjusted_rand_score(labels_true, labels_pred)
print("ARI = ", adjusted_rand_score(labels_num, hc_model.labels_))

import scipy.cluster.hierarchy as shc
plt.figure(figsize=(10, 7))
plt.title("Iris Dendrogram")
dend = shc.dendrogram(shc.linkage(features, method='ward'))

plt.scatter(features[:,0], features[:,1], c=labels, cmap='rainbow')