# -*- coding: utf-8 -*-
"""Classification Problems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144roZWQkVX9czl0n8ygmpgfbogPByukj
"""

import pandas as pd
import numpy as np
import seaborn as sns

customer = pd.read_csv('customer_churn.csv')

customer.head()

customer = customer.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

X = customer.drop('Exited', axis=1)
y = customer['Exited']

X.head()

y.head()

numeric = X.drop(['Geography', 'Gender'], axis=1)
numeric.head()

categorically = X.filter(['Geography', 'Gender'])
categorically.head()

cat_numerical = pd.get_dummies(categorically, drop_first=True)
cat_numerical.head()

X = pd.concat([numeric, cat_numerical], axis=1)
X.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)

from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression()
classifier = log_clf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
plt.rcParams['figure.figsize'] = (8, 6)
corr = X.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accurancy: ", accuracy_score(y_test, y_pred))

from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=5)
classifier = knn_clf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accurancy: ", accuracy_score(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier
rf_cf = RandomForestClassifier(random_state=42, n_estimators=500)
classifier = rf_cf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accurancy: ", accuracy_score(y_test, y_pred))

from sklearn import svm
svm_clf = svm.SVC()
classifier = svm_clf.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accurancy: ", accuracy_score(y_test, y_pred))

from sklearn.model_selection import cross_val_score
print(cross_val_score(classifier, X, y, cv=5, scoring='accuracy').mean())

customer.loc[105]

from sklearn.ensemble import RandomForestClassifier
rf_cf = RandomForestClassifier(random_state=42, n_estimators=500)
classifier = rf_cf.fit(X_train, y_train)
single_record = sc.transform(X.values[105].reshape(1, -1))
predicted_churn = classifier.predict(single_record)
print(predicted_churn)

from sklearn.metrics import roc_curve, roc_auc_score

y_pred_prob = rf_cf.predict_proba(X_test)[:,1 ]

fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob, pos_label=1)

# C o m p u t e t h e R O C A U C s c o r e
roc_auc = roc_auc_score(y_test, y_pred_prob)
roc_auc

plt.plot(fpr, tpr, label = 'ROC curve (are a = % 0.2f) ' % roc_auc)

plt.plot([0 , 1] , [0 , 1], 'k--', label = ' Random classifier')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc = "lower right")
plt.show( )