# -*- coding: utf-8 -*-
"""ClusteringSummativeProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMoce781DLGYlz0gxZal_kdtxlyIZ2xh

Countries of the World

The target field is the countries of the world in which country names are usually linked into factors such as region, area size, GDP, mortality and much more. The things that are tried to be predicted here are region based on the factors of population density and net migration.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
# %matplotlib inline

"""Link to the dataset: https://www.kaggle.com/datasets/fernandol/countries-of-the-world

"""

countries_world = pd.read_csv('countries of the world (1).csv')
countries_world.head()

features = countries_world.drop(['Region', 'Country', "Area (sq. mi.)"], axis=1)
labels = countries_world.filter(['Region'], axis=1)
features.head()

features = features.fillna(0)
features = features.values
km_model = KMeans(n_clusters=5)
km_model.fit(features)

print(km_model.labels_)

plt.scatter(features[:,5], features[:,7], c=km_model.labels_, cmap='rainbow')
plt.scatter(km_model.cluster_centers_[:,5], km_model.cluster_centers_[:,7], s=100, color='black')

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score
print("ARI = ", adjusted_rand_score(labels_num, km_model.labels_))

loss = []
for i in range(1, 11):
  km  = KMeans(n_clusters = i).fit(features)
  loss.append(km.inertia_)

import matplotlib.pyplot as plt
plt.plot(range(1, 11), loss)
plt.title('Finding Optimal ')
plt.xlabel('Number of clusters')
plt.ylabel('Loss')
plt.show()

km_model = KMeans(n_clusters=6)
km_model.fit(features)

plt.scatter(features[:, 5], features[:,7], c=km_model.labels_, cmap='rainbow')
plt.scatter(km_model.cluster_centers_[:,5], km_model.cluster_centers_[:,7], s=100, color='black')

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

plt.scatter(features[:,5], features[:,7], c=labels_num, cmap='rainbow')

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
labels_num = le.fit_transform(labels)

from sklearn.metrics.cluster import adjusted_rand_score

print("ARI = ", adjusted_rand_score(labels_num, km_model.labels_))

plt.scatter(features[:,5], features[:,7])
annots = range(1,11)
for label,x,y in zip(annots, features[:,5], features[:, 7]):
  plt.annotate(label,xy = (x,y) , xytext = (-3,3), textcoords = 'offset points', ha = 'right', va = 'bottom')
plt.show()

import scipy.cluster.hierarchy as sch
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 7))
plt.title("Dendrogram")
dendogram = sch.dendrogram(sch.linkage(features, method='ward'))
plt.axhline(y=6, color='r', linestyle='--')
plt.show()

from sklearn.cluster import AgglomerativeClustering
hc_model = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
labels = hc_model.fit_predict(features)

plt.scatter(features[:, 5], features[:, 7], c=hc_model.labels_, cmap = 'rainbow')

"""Reportings

The data shows an ARI of 0.014 for predicting region between net migration and population density indicating there is little to no correlation between those two factors for predicting region. Since region cannot be predicted using only population density and net migration, other factors such as GDP per capita must be used to determine the predictability of a region.
"""