# -*- coding: utf-8 -*-
"""DataVisualizationProject(SurdeepThota).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsaVJPWdle7WwgksJ58BhpD2H66Clt5a
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
import math
import pandas as pd

data = pd.read_csv('banknote.csv')
data1= pd.read_csv('heart.csv')

data.head()

data1.head()

x_vals = data1['age']
y_vals = data1['exang']
plt.plot(x_vals, y_vals)

"""The story that it tells here is the fact the majority of people who get exang or exercise induced angina are people usually over the age of 40 indicating a trend in which as the person gets older, they will get a higher chance of exang."""

# @title variance vs skewness
#scatterplot
plt.scatter(data['variance'], data['skewness'])
plt.xlabel('variance')
plt.ylabel('skewness')
plt.title("Variance vs Skewness")

"""The story that it tells here is that fact that variance and skewness of the bank data are very correlated in that the fact it is shaped into clusters. This means that there is a specific range of skewness for each range of variance. Also the diagram above shows that there could specific ranges of skewness that could be used in multiple ranges of variance indicating versatility."""

plt.xlabel("skewness")
plt.ylabel("entropy")
plt.bar(data['skewness'], data['entropy'])
plt.title("Skewness vs Entropy")
#bar graph

"""The story depicts a similar looking bell curve except in the extreme low and high ranges of skewness, the entropy is negative indicating that the money is going in the negative way unpredicatable. However within the middle ranges of skewness, the entropy has a high chance of being positive indicating that the money is trending positively unpredictably."""

plt.title("Skewness Histogram")
plt.hist(data["skewness"])

"""The story depicts that higher skewness ranges tend to be in more abundance than negative skewness indicating that the data is skewed positively or the data within the financial market is more positively wanting to go within the positiive direction."""

labels = 'variance', "skewness", "curtosis", 'entropy', 'class'
values = [500,156,300,510, 435]
explode = (0.05, 0.05, 0.05, 0.05, 0.05)
plt.pie(values, explode=explode, labels=labels,
autopct='%1.1f%%', shadow=True)
plt.show()
#pie chart

"""The story depicts the "class", "variance", and "entropy" classifiers as some of the most important measurements in determining how the data within banknote.csv is. Since they are roughly equivalent in proportion, they should be considered equally when deciding whether or not the market is trending positively."""

plt.rcParams["figure.figsize"] = [10,8]
data = pd.read_csv("banknote.csv")
data.head()

import seaborn as sns
plt.rcParams["figure.figsize"] = [10,8]
sns.distplot(data['skewness'])
#distplot

"""The story shows a bell curve that has been skewed to the left indicating that the density has more in abundance as the skewness increases indicating that the market prediction for each of the prediction will tend to be more accurate within the upper middle portions of the graph."""

sns.jointplot(x='variance', y='skewness', data=data)
#combined plots

"""The story here depicts a with the variance histogram being uniform after the going past the few initial stages of the low variance values with skewness having a bimodal graph skewed to the right. This indicates that variance doesn't "correlate" with skewness but rather within specific range for each of the variables since it is in a cluster format not linear format."""

sns.jointplot(x='variance', y='skewness', data=data, kind='reg')
#extra lines

"""Even though there is a line within the graph, it doesn't depict the overall graph well since there are too many values that are far away from the line of best fit indicating that linearizing the data would not be good."""

sns.pairplot(data=data)

#bunch of plots

"""Here, it shows 20 graphs detailing the different trends between all of them with most of them having a strong correlation to each other indicating that all of these factors play a role within the financial markets and are intertwined with each other."""

plt.rcParams["figure.figsize"] = [8,6]
sns.set_style("darkgrid")
data1 = pd.read_csv('heart.csv')
data.head()

sns.barplot(x='age', y='exang', data=data1)

#barplot

"""This depicts that age and exang have little to no correlation with each other because the lower and higher ranges of age tend to have higher exang values while the middle ranges have lower age to exang values."""

sns.countplot(x='exang', data=data1)
plt.xlabel("exang")
plt.title("exang count")

"""This indicates that the 66% of people don't have exercise induced angina indicating that there is a high chance of around 33% that the individual may get exang which should alert the individual to make healthier life choices."""

sns.boxplot(x=data1["age"])
plt.xlabel("age")
plt.title("age boxplot")

"""This shows the range of participants within the dataset of heart.csv since most are between the ages of 50 and 60 with the youngest being less than 30 and oldest being over 70."""

sns.violinplot(x='age', y='exang', data=data1)
plt.xlabel("age")
plt.ylabel("exang")
plt.title("age vs exang")

"""The story here depicts a visualization in which it details the percent of which the person with a specific exang would receive in accordance to their age. Since exang is either 1 or 0, there are a lot of black lines signaling emptiness within those values."""

data1['age'].hist()
plt.xlabel("age")
plt.ylabel("count")
plt.title("age histogram")

"""It shows that the mode is in between 55 and 65 years old indicating that older adults have an higher representation within the dataset which could shows bias when trying to see correlations between all the different factors within the heart.csv dataset."""

heart = pd.read_csv('heart.csv')
heart.head()

heart.plot.line(y='age', figsize=(8,6))
plt.xlabel("age")
plt.title("age")

"""The story here depicts the number of people for each age value indicating that the data may have some discrepancies due to the count being higher for values above 100 signaling inaccurancies for the values.  """

heart.plot.scatter(x='fbs', y='thalach', figsize=(8,6))
plt.xlabel("fbs")
plt.ylabel("thalach")
plt.title("fbs vs thalach")

"""This indicates that maximum heart rate (thalach) only occurs whether the individual has over 120 mg/dl (1 = true) or not (0=false). Since thalach occurs more often in individuals under 120 mg/dl than not, this indicates a positive correlation between maximum heart rate as well as fasting blood sugar."""

exang_mean = heart.groupby("sex")["exang"].mean()
print(exang_mean)
print(type(exang_mean.tolist()))

df = pd.DataFrame({'gender':['Female', 'Male'], 'age':exang_mean.tolist()})
ax = df.plot.bar(x='gender', y='age', figsize=(8,6))

"""The dataset of heart.csv shows a trend in which men are more to get exang than women indicating that men on average tend to get more diseases due to exercising than women. There could be confounding variables such as men on average taking more laborous jobs than women but overall women tend to not get them that often."""