# -*- coding: utf-8 -*-
"""DataVisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZM1aWydBA14z-VRdArwpjajx7LnvnccQ
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.plot(x_vals, y_vals)

import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]

fig = plt.figure()
ax = plt.axes()
ax.plot(x_vals, y_vals)

import matplotlib.pyplot as plt
import numpy as np
import math

plt.rcParams['figure.figsize'] = [8, 6]

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.plot(x_vals, y_vals)

import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.xlabel("X Values")
plt.ylabel("Y Values")
plt.title("Square Root Graph")
plt.plot(x_vals, y_vals)

import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.xlabel("X Values")
plt.ylabel("Y Values")
plt.title("Square Root Graph")
plt.plot(x_vals, y_vals, "r")

import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.xlabel("X Values")
plt.ylabel("Y Values")
plt.title("Square Root Graph")
plt.plot(x_vals, y_vals, "r", label = "Square Roots")
plt.legend(loc = "upper center")

import matplotlib.pyplot as plt
import numpy as np
import math

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.xlabel("X Values")
plt.ylabel("Y Values")
plt.title("Square Root Graph")
plt.plot(x_vals, y_vals, "r", label = "Square Roots")
plt.plot(x_vals, y_vals, "b", label = "Cube")
plt.legend(loc = "upper center")

import pandas as pd
import seaborn as sns
data = sns.load_dataset("iris")
data.head()

data.head()

plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.title('Sepal vs. Petal Length')
plt.plot(data['sepal_length'], data['petal_width'], "b")

import pandas as pd
data = sns.load_dataset("iris")
data.head()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import math

plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.title('Sepal vs. Petal Length')
plt.scatter(data['sepal_length'], data['petal_width'], c="b")

import pandas as pd
data = sns.load_dataset("titanic")
data.head()

plt.xlabel('Gender')
plt.ylabel('Ages')
plt.title('Gender vs Age')
plt.bar(data['sex'], data['age'])

plt.title("Age Histogram")
plt.hist(data['age'])

labels = 'IT', "Marketing", "Adta Science", "Finance"
values = [500, 156, 300, 510]
explode = (0.05, 0.05, 0.05, 0.05)
plt.pie(values, labels=labels, explode=explode, shadow=True, autopct='%1.1f%%')
plt.show()

plt.rcParams["figure.figsize"] = [10, 8]
tips_data = sns.load_dataset("tips")
tips_data.head()

plt.rcParams["figure.figsize"] = [10, 8]
sns.displot(tips_data)

sns.jointplot(x='total_bill', y='tip', data=tips_data)

sns.jointplot(x='size', y='total_bill', data=tips_data, kind='reg')

sns.pairplot(data=tips_data)

plt.rcParams["figure.figsize"] = [8, 6]
sns.set_style("darkgrid")
titanic_data = sns.load_dataset("titanic")
titanic_data.head()

sns.barplot(x="pclass", y="age", data=titanic_data)

sns.countplot(x="pclass", data=titanic_data)

sns.boxplot(x=titanic_data["fare"])

sns.violinplot(x='alone', y='age', data=titanic_data)

titanic_data['age'].hist()

flights_data=sns.load_dataset("flights")
flights_data.head()

flights_data.plot.line(y="passengers", figsize = (8,6))

flights_data.plot.scatter(x='year', y='passengers', figsize=(8,6))

sex_mean = titanic_data.groupby("sex")["age"].mean()
print(sex_mean)
print(type(sex_mean.tolist()))

df = pd.DataFrame({'gender':['Female', 'Male'], 'age':sex_mean.tolist()})
ax = df.plot.bar(x='gender', y='age', figsize=(8,6))

