# -*- coding: utf-8 -*-
"""DeepLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FgWAO_zlu8Ovp2-a9HMhd4BKvoVmL5lq
"""

import tensorflow as tf
print(tf.__version__)
import seaborn as sns
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam

banknote_data = pd.read_csv("banknote.csv")

banknote_data.head()

banknote_data.shape

sns.countplot(x='class', data=banknote_data)

X = banknote_data.drop(["class"], axis=1).values
y= banknote_data[['class']].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

def create_model(learning_rate, dropout_rate):
    model = Sequential()
    model.add(Dense(12, input_dim=X_train.shape[1], activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(6, activation='relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    adam = Adam(learning_rate)
    model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
    return model

dropout_rate = 0.1
epochs = 20
batch_size=4
learn_rate=0.001

model = create_model(learn_rate, dropout_rate)

from tensorflow.keras.utils import plot_model
plot_model(model, to_file='model_plot1.png', show_shapes=True, show_layer_names=True)

model_history = model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2, verbose=1)

accurancies = model.evaluate(X_test, y_test, verbose=1)
print("Test Score:", accurancies[0])
print("Test Accurancy:", accurancies[1])

history_dict=model_history.history
print(history_dict.keys())

import matplotlib.pyplot as plt
plt.plot(model_history.history['accuracy'], label = 'accuracy')
plt.plot(model_history.history['val_accuracy'], label='val_accuracy')
plt.legend(['train', 'test'], loc = 'lower left')

plt.plot(model_history.history['loss'], label='loss')
plt.plot(model_history.history['val_loss'], label='val_loss')
plt.legend(['train', 'test'], loc='upper left')