# -*- coding: utf-8 -*-
"""Fun Data Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIynbomAmGUIA-doUCNHhrcHMMshwPSY
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
import math
import pandas as pd

"""# Line Graphs"""

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.plot(x_vals, y_vals)

fig = plt.figure()
ax = plt.axes()
ax.plot(x_vals, y_vals)

plt.rcParams["figure.figsize"] = [8,6]
x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.plot(x_vals, y_vals)

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title("Square Roots")
plt.plot(x_vals, y_vals)

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title("Square Roots")
plt.plot(x_vals, y_vals, 'r')

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title("Square Roots")
plt.plot(x_vals, y_vals, 'r', label = 'Square Root')
plt.legend(loc='upper center')

x_vals = np.linspace(0, 20, 20)
y_vals = [math.sqrt(i) for i in x_vals]
y2_vals = x_vals ** 3
plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title("Square Roots")
plt.plot(x_vals, y_vals, 'r', label = 'Square Root')
plt.plot(x_vals, y2_vals, 'b', label = 'Cube')
plt.legend(loc='upper center')

import seaborn as sns

data = sns.load_dataset("iris")
data.head()

plt.xlabel('Sepal Length')
plt.ylabel('Petal Length')
plt.title('Sepal vs Petal Length')
plt.plot(data["sepal_length"], data["petal_length"], 'b')

import pandas as pd

"""# Scatter Plot"""

plt.xlabel('Sepal Length')
plt.ylabel('Petal Length')
plt.title('Sepal vs Petal Length')
plt.scatter(data["sepal_length"], data["petal_length"], c = 'b')

data = sns.load_dataset("titanic")
data.head()

"""# Bar Graph"""

plt.xlabel('Gender')
plt.ylabel('Ages')
plt.title('Gender vs Age')
plt.bar(data["sex"], data["age"])

"""# Histogram"""

plt.title("Age Histogram")
plt.hist(data["age"])

"""# Crime Against Humanity and Data Scientists"""

labels = 'IT', "Marketing", "Adta Science", 'Finance'
values = [500,156,300,510]
explode = (0.05, 0.05, 0.05, 0.05)
plt.pie(values, explode=explode, labels=labels,
autopct='%1.1f%%', shadow=True)
plt.show()

plt.rcParams["figure.figsize"] = [10,8]
tips_data = sns.load_dataset('tips')
tips_data.head()

"""# Dist Plot"""

plt.rcParams["figure.figsize"] = [10,8]
sns.distplot(tips_data['total_bill'])

"""# Joint Plots"""

sns.jointplot(x='total_bill', y='tip', data=tips_data)

sns.jointplot(x='size', y='total_bill', data=tips_data, kind = 'reg')

"""# Bunch of Plots"""

sns.pairplot(data=tips_data)

plt.rcParams["figure.figsize"] = [8,6]
sns.set_style("darkgrid")
titanic_data = sns.load_dataset('titanic')
titanic_data.head()

"""# Bar Plot"""

sns.barplot(x='pclass', y='age', data=titanic_data)

"""# Count Plot"""

sns.countplot(x='pclass', data=titanic_data)

"""# Box Plot"""

sns.boxplot(x=titanic_data["fare"])

"""# Violin Plot"""

sns.violinplot(x='alone', y='age', data=titanic_data)

"""# Example Stuffs"""

titanic_data['age'].hist()

flights_data = sns.load_dataset('flights')
flights_data.head()

flights_data.plot.line( y='passengers', figsize=(8,6))

flights_data.plot.scatter(x='year', y='passengers', figsize=(8,6))

sex_mean = titanic_data.groupby("sex")["age"].mean()
print(sex_mean)
print(type(sex_mean.tolist()))

df = pd.DataFrame({'gender':['Female', 'Male'], 'age':sex_mean.tolist()})
ax = df.plot.bar(x='gender', y='age', figsize=(8,6))