# -*- coding: utf-8 -*-
"""itemBasedCollaborativeFilteringNotes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtHb552xOl-Vh36IV1UIbhxWIgQraaHu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

movie_ids_titles = pd.read_csv(r"/content/drive/MyDrive/data/movies.csv", 0)

movies_ids_titles.head()

movies_ids_ratings = pd.read_csv(r"/content/drive/MyDrive/data/ratings.csv")
movies_ids_ratings.head()

movies_ids_ratings.shape
#shape of the dataframe

movies_ids_titles.drop("genres", inplace = True, axis = 1)
movies_ids_titles.head()

#datapreprocessng - removes genres from the titles since we want to merge titles and ratings

movies_ids_ratings.drop("timestamp", inplace = True, axis = 1)
movies_ids_ratings.head()

merged_movie_df = pd.merge(movie_ids_ratings, movie_ids_titles, on = 'movieId')
merged_movie_df.head()

merged_movie_df.groupby('title').describe()

merged_movie_df.groupby('title')['rating'].mean().head()

merged_movie_df.groupby('title')['rating'].mean().sort_values(ascending=False).head()

merged_movie_df.groupby('title')['rating'].count().sort_values(ascending=False).head()

movie_rating_mean_count = pd.DataFrame(columns = ['rating_mean', 'rating_count'])

movie_rating_mean_count['rating_mean'] = merged_movie_df.groupby('title')['rating'].mean()

movie_rating_mean_count['rating_count'] = merged_movie_df.groupby('title')['rating'].count()


movie_rating_mean_count.head()

plt.figure(figsize=(10, 8))
sns.set_style("darkgrid")

movie_rating_mean_count['rating_mean'].hist(bins = 30, color = "purple")

plt.figure(figsize= (10, 8))
sns.set_style("darkgrid")
movie_rating_mean_count['rating_mean'].hist(bins = 30, color = "green")

plt.figure(figsize= (10, 8))
sns.set_style("darkgrid")


sns.regplot(x="rating_mean", y="rating_count", data = movie_rating_mean_count, color="brown")

movie_rating_mean_count.sort_values("rating_count", ascending=False).head()

user_movie_rating_matrix = merged_movie_df.pivot_table(index='userId', columns = 'title', values = 'rating')

user_movie_rating_matrix

user_movie_rating_matrix.shape

pulp_fiction_ratings = user_movie_rating_matrix["Pulp Fiction (1994)"]

pulp_fiction_correlations = pd.DataFrame(user_movie_rating_matrix.corrwith(pulp_fiction_ratings), columns = ["pf_corr"])

pulp_fiction_correlations.sort_values("pf_corr", ascending = False).head(5)

pulp_fiction_correlations = pd.DataFrame(user_movie_rating_matrix.corrwith(pulp_fiction_ratings), columns = ["pd_corr"])

pulp_fiction_correlations.sort_values("pf_corr", ascending = False).head(5)

pulp_fiction_correlations = pulp_fiction_correlations.join(movie_rating_mean_count["rating_count"])

pulp_fiction_correlations.head()

pulp_fiction_correlations.dropna(inplace = True)

pulp_fiction_correlations.sort_values("pd_corr", asccending = False).head(5)

pulp_fiction_correlations_50 = pulp_fiction_correlations[pulp_fiction_correlations['rating_count']>50]
pulp_fiction_correlations_50.sort_values('pf_corr', ascending = False).head()

all_movie_correlations = user_movie_rating_matrix.corr(method = 'pearson', min_periods  = 50)
all_movie_correlations.head()

movie_data = [['Forrest Gump (1994)', 4.0], ['Fight Club (1999)', 3.5], ['Instellar (2014)', 4.0]]
test_movies = pd.DataFrame(movie_data, columns = ['Movie_Name', 'Movie_Rating'])
test_movies.head()

print(test_movies['Movie_Name'][0])
print(test_movies['Movie_Rating'][0])

all_movie_correlations['Forrest Gump (1994)'].dropna()

recommended_movies = pd.Series()
for i in range(0, 2):
  movie = all_movie_correlations[test_movies['Movie_Name'][i]].dropna()
  movie = movie.map(lambda movie_corr: movie_corr * test_movies['Movie Rating'][i])
  recommended_movies = pd.concat([recommended_movies, movie])

recommended_movies.sort_values(inplace = True, ascending = False)
recommended_movies.head(10)