# -*- coding: utf-8 -*-
"""LLMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfCWd27dsvPJl6MLPTGDHoJ4Mlz2wrny
"""

import io
import random
import string
import warnings
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('popular', quiet=True)
!pip install spacy
!python -m spacy download en_core_web_sm
!pip install -U NLTK
!pip install scipy
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
# Download required NLTK data
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

import requests
from bs4 import BeautifulSoup

url = "https://www.allrecipes.com/recipe/24074/alysias-basic-meat-lasagna/"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

title = soup.find("h1").text.strip()
ingredients = [i.text.strip() for i in soup.select(".ingredients-item-name")]
steps = [s.text.strip() for s in soup.select(".instructions-section-item p")]

print("Title:", title)
print("Ingredients:", ingredients)
print("Steps:", steps)

raw=text_data
raw = raw.lower()# converts to lowercase
sent_tokens = nltk.sent_tokenize(raw)# converts to list of sentences
word_tokens = nltk.word_tokenize(raw)# converts to list of words
lemmer = nltk.stem.WordNetLemmatizer()
#WordNet is a semantically-oriented dictionary of English included in NLTK.
def LemTokens(tokens):
  return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def LemNormalize(text):
  return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey","yo")
GREETING_RESPONSES = ["hi", "hey", "*nods*", "hi there", "hello", "I am glad! You are talking to me"]
def greeting(sentence):
  for word in sentence.split():
    if word.lower() in GREETING_INPUTS:
      return random.choice(GREETING_RESPONSES)

def response(user_response):
  spar_response=''
  sent_tokens.append(user_response)
  TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
  tfidf = TfidfVec.fit_transform(sent_tokens)
  vals = cosine_similarity(tfidf[-1], tfidf)
  idx=vals.argsort()[0][-2]
  flat = vals.flatten()
  flat.sort()
  req_tfidf = flat[-2]
  if(req_tfidf==0):
    spar_response=spar_response+"I don't understand you"
    return spar_response
  else:
    spar_response = spar_response+sent_tokens[idx]
    return spar_response

flag=True
print("Tim: My name is Tim. I will answer your queries about Soccer. If you want to exit, type bye!")
while(flag==True):
  user_response = input()
  user_response=user_response.lower()
  if(user_response!='bye'):
    if(user_response=='thanks' or user_response=='thank you' ):
      flag=False
      print("Tim: You are welcome..")
    else:
      if(greeting(user_response)!= None):
        print("Tim: " + greeting(user_response))
      else:
        print("Tim: ",end="")
        print(response(user_response))
        sent_tokens.remove(user_response)
  else:
    flag=False