# -*- coding: utf-8 -*-
"""MarketWatch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZid6XBMnRh0NxX5HgJEo7y85Ars7_mw
"""

import pandas as pd
import numpy as np
import difflib

microsoft_stock = pd.read_csv('microsoft_stock_training2.csv')
headers = microsoft_stock.iloc[0].values
microsoft_stock.columns = headers
microsoft_stock.drop(index=0, axis=0, inplace=True)
microsoft_stock = microsoft_stock.reset_index(drop=True)
print(microsoft_stock.head())

#prints out the dataset

microsoft_stock.columns = microsoft_stock.columns.str.strip()
print(microsoft_stock.columns)

#removes the string
#checks the columns to see any issues

microsoft_stock = pd.read_csv("microsoft_stock_training2.csv", encoding='utf-8')
print(microsoft_stock.head())

#one - hot coding to fix the code

print(microsoft_stock.dtypes)

microsoft_stock['Open'] = pd.to_numeric(microsoft_stock['Open'], errors='coerce')
#make Open column into a different data type

microsoft_stock_processed = microsoft_stock[['Open']].values
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
microsoft_stock_scaled = scaler.fit_transform(microsoft_stock_processed)
len(microsoft_stock_scaled)
#scales the data

microsoft_stock["Open"]

#details whether or not the open column works or not

print('Open' in microsoft_stock.columns)  # Should return True if 'Open' exists
#should be True if it exists

microsoft_stock_training_features = []
microsoft_stock_training_labels = []
for i in range(60, len(microsoft_stock_scaled)):
    microsoft_stock_training_features.append(microsoft_stock_scaled[i-60:i, 0])
    microsoft_stock_training_labels.append(microsoft_stock_scaled[i, 0])

#divides the data into training and testing data

X_train = np.array(microsoft_stock_training_features)
y_train = np.array(microsoft_stock_training_labels)

print(X_train.shape)
print(y_train.shape)

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Activation, Dense, Flatten, Dropout, Flatten, LSTM
from tensorflow.keras.models import Model
if len(X_train.shape) < 2:
    X_train = X_train.reshape(-1, 1)  # Reshape to (samples, 1 feature)

input_layer=Input(shape=(X_train.shape[1], 1))
lstm1 = LSTM(100, activation = 'relu', return_sequences = True)(input_layer)
do1 = Dropout(0.2)(lstm1)
lstm2 = LSTM(100, activation = 'relu', return_sequences = True)(do1)
do2 = Dropout(0.2)(lstm2)
lstm3 = LSTM(100, activation = 'relu', return_sequences = True)(do2)
do3  = Dropout(0.2)(lstm3)
lstm4 = LSTM(100, activation="relu")(do3)
do4 = Dropout(0.2)(lstm4)
output_layer = Dense(1)(do4)
model = Model(input_layer, output_layer)
model.compile(optimizer='adam', loss='mse')

from tensorflow.keras.utils import plot_model
plot_model(model, to_file='model.png', show_shapes=True, show_layer_names=True)

print(X_train.shape)
print(y_train.shape)
y_train = y_train.reshape(-1,1)
print(y_train.shape)

model_history = model.fit(X_train, y_train, epochs=20, verbose=1, batch_size=32)

microsoft_testing_complete_data=pd.read_csv("microsoft_stock_testing2 copy.csv")
headers = microsoft_testing_complete_data.iloc[0].values
microsoft_testing_complete_data.columns = headers
microsoft_testing_complete_data.drop(index=0, axis=0, inplace=True)
microsoft_testing_complete_data = microsoft_testing_complete_data.reset_index(drop=True)
microsoft_testing_processed=microsoft_testing_complete_data["Open"].values
microsoft_all_data=pd.concat((microsoft_stock["Open"],microsoft_testing_complete_data["Open"]),axis=0)
test_inputs = microsoft_all_data[len(microsoft_all_data) - len(microsoft_testing_complete_data) - 60:].values
print(test_inputs.shape)

#it reshapes all of the data into different variables for further use in the procedures found later in this

microsoft_testing_complete_data

test_inputs = test_inputs.reshape(-1,1)
test_inputs = scaler.transform(test_inputs)
print(test_inputs.shape)

microsoft_stock_testing_features = []
for i in range(60, 80):
  microsoft_stock_testing_features.append(test_inputs[i-60:i, 0])

X_test=np.array(microsoft_stock_testing_features)
print(X_test.shape)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
print(X_test.shape)
y_pred = model.predict(X_test)  # X_test is your input test set

# Reshape for inverse transformation
y_pred = y_pred.reshape(-1, 1)
microsoft_testing_processed = microsoft_testing_processed.reshape(-1, 1)

# Apply inverse transformation
y_pred_original = scaler.inverse_transform(y_pred)
actual_original = scaler.inverse_transform(microsoft_testing_processed)
y_pred_original = scaler.inverse_transform(np.concatenate([y_pred, np.zeros_like(y_pred)], axis=1))[:, 0]

print("Min and Max of y_pred before inverse transform:", y_pred_original.min(), y_pred.max())
print("Min and Max of actual values before inverse transform:", microsoft_testing_processed.min(), microsoft_testing_processed.max())
#it tells the y-prediction before and after

import matplotlib.pyplot as plt

# Ensure the predicted and actual values are reshaped correctly before inverse transforming
y_pred = scaler.inverse_transform(y_pred.reshape(-1, 1))
microsoft_testing_processed = scaler.inverse_transform(microsoft_testing_processed.reshape(-1, 1))

# Plot the corrected values
plt.figure(figsize=(16,8))
plt.plot(microsoft_testing_processed, color='red', label='Actual Microsoft Stock Price')
plt.plot(y_pred, color='green', label='Predicted Microsoft Stock Price')
plt.title('Microsoft Stock Price')
plt.xlabel('Date')
plt.ylabel('Stock Price')
plt.legend()
plt.show()

#all of this details the predicted price of Microsoft Stock price vs the date