# -*- coding: utf-8 -*-
"""Movie Database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxbSUF54CZLJUqvlrka1Wo4OqjsFdJPU
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('https://runestone.academy/ns/books/published/httlads/_static/movies_metadata.csv').dropna(axis=1, how='all')
df.head()

budget_df = df[df["budget"] > 1000000]
budget_df.shape

budget_lookup = pd.Series(data = df["budget"].values, index = df['title'])
budget_lookup["Dead Presidents"]

budget_df_sorted = budget_df.sort_values('title')
movies_with_as_and_bs = budget_df_sorted[budget_df_sorted['title'].str[0].isin(['A', 'B'])]
count = movies_with_as_and_bs.shape[0]
print(count)

df['runtime'] = pd.to_numeric(df["runtime"], errors = "coerce")
df_filtered = df[(df['runtime'] >= 10) & (df['runtime'] <= 180)]
time_scheduler = pd.Series(data=df_filtered['title'].values, index=df_filtered['runtime'])
time_scheduler = time_scheduler.sort_index()
print(time_scheduler.head())

movies_154_minutes = time_scheduler.loc[154]
count_154_minutes = movies_154_minutes.shape[0] if isinstance(movies_154_minutes, pd.Series) else 1
print(count_154_minutes)

shortest_movies = time_scheduler.sort_index()
movie_155 = shortest_movies.iloc[154]
print(movie_155)

df_highly_voted = df[df.vote_count > 20]
df_high_rated = df_highly_voted[df_highly_voted.vote_average > 8]
df_high_rated[['title', 'vote_average', 'vote_count']].head()

high_rated_count = df_high_rated.shape[0]
high_rated_count

my_votes = {
    "Star Wars": 9,
    "Paris is Burning": 8,
    "Dead Poets Society": 7,
    "The Empire Strikes Back": 9.5,
    "The Shining": 8,
    "Return of the Jedi": 8,
    "1941": 8,
    "Forrest Gump": 7.5,
}

my_ratings = pd.Series(my_votes).rename("my_votes")
print(my_ratings)
cv = df_high_rated.set_index('title')
cv = cv.join(my_ratings).dropna(axis=0)
cv['percent_difference'] = 100 * (cv['vote_average'] - cv['my_votes']) / cv['my_votes']

cv

"""3 Questions:

Is there a movie with a 8.1 star rating?

What is the longest movie?

What is the shortest movie?

Answer:

Some movies with a 8.1 star rating are Se7en, The Usual Suspects, Taxi Driver, and Star Wars.

The longest movie is 1256 minutes long.

The shortest movie is 0 minutes long.
"""

df_high_rated = df[df.vote_average > 8]
df_high_rated[['title', 'vote_average', 'vote_count']].head()

print(df['runtime'].max())

print(df['runtime'].min())