# -*- coding: utf-8 -*-
"""Naïve Bayes Algorithm / Regular Regressions(Sorting Algorithm used for sorting spam).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3Paoo6X5lnoFLcboTICv8PfcN9lZNpM

### Regular Expressions

- characters in specific order helping programmers find sequences of characters/strings using syntax in the system
- supports the regular expressions through the standard Python libraries

### Raw Strings in Python

- better to use raw strings than regular strings
- begin raw strings with "r", backslashes, and special meta characters
- helps pass regular-expression-engine

### Match Function
-- used to test whether or not a regular expression matches a specific string in python
* re.match()
- returns none of the pattern when it doesn't match or additional information about the string in which the method is found
---
- re.match (pattern, string, flags=0)
* match(): is a method
* pattern: this is the regular expression that uses meta-characters to describe what strings can be matched.
* string: is used to search & match the pattern at the string's initiation.
flags: programmers can identify different flags using bitwise operator '|' (OR)
"""

import re    #simple structure of re.match()
        matchObject = re.match(pattern, input_str, flags=0)

"""A program using re.match()"""

import re
list = [ "mouse", "cat", "dog", "no-match"]
# Loop starts here
for elements in list:
    m = re.match("(d\w+) \W(d/w+)" , element)
# Check for matching
if m:
    print (m . groups ( ))

"""-Uses meta-character to describe which strings it can match in the above program
- '\w' means word-character
- + (plus symbol denoting one or more)

### search Function

- attempts at all possible starting points in the string
- scans through the input string and tries to match at any location
- Syntax: re.search( pattern, strings, flags=0)
"""

import re
value = "cyberdyne"
g = re.search("(dy.*)",  value)
if g:
    print("search: ", g.group(1))
s = re.match("(vi.*)", value)
if s:
    print("match:", m.group(1))

"""### split Function
- re.split() accepts pattern that specifies the delimiter
- match the pattern and separate text data
-avaliable directly on string and handles no regular expression
"""

import re
value = "two 2  four 4  six 6"
#separate those non-digit characters
res = re.split ("\D+" , value)
# print the result
for elements in res :
    print (elements)

"""In the above program, \D+ represents one or more non-digit characters.


"""