# -*- coding: utf-8 -*-
"""Project 1 - Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGjox2xOx8suJffAlJeRkOPe_oApFOVk
"""

import pandas as pd
import numpy as np
import seaborn as sns

housing_dataset = pd.read_csv("BostonHousing.csv").dropna()

# Commented out IPython magic to ensure Python compatibility.
housing_dataset.describe()

import matplotlib.pyplot as plt
# %matplotlib inline
plt.rcParams["figure.figsize"] = [8,6]
corr = housing_dataset.corr()
corr

sns.heatmap(corr)

X = housing_dataset.drop(['medv'], axis=1)
y = housing_dataset["medv"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression( )
regressor = lin_reg.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R²:', metrics.r2_score(y_test, y_pred))

from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=5)
regressor = knn_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(random_state=42, n_estimators=500)
regressor = rf_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

